body:
  - type: markdown
    attributes:
      value: >
        ⚠️ This category is solely for discussions and feedback on GitHub Enterprise Cloud & Enterprise Server, 
        as well as GitHub Enterprise administration. ⚠️

     The Enterprise category is NOT meant to be a place to submit Support requests. 
     You must Contact GitHub Support to open a Support ticket.
     
  - type: dropdown
    attributes:
      label: Select Topic Area
      description: What would you like to discuss?
      options:
        - Question
        - Product Feedback
        - Bug
        - Show & Tell
        - General
    validations:
      required: true
  - type: textarea
    attributes:
      label: Body
      description: Start your discussion!
    validations:
      required: true
- type: checkboxes
    attributes:
      label: Guidelines
      options:
        - label: I have read the above statement and am aware that I am not opening a Support ticket 
        by creating a Discussion in this channel.
          required: true
